### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by i-sachinkumar** [Subhash91134857/Sorting-Visualizer#1]
Click the `Generate Array` button multiple times and see.
basically,  it's not clearing the previous data (see screenshot)
<img width="956" alt="issue_img" src="https://user-images.githubusercontent.com/81405044/183059342-e362b56e-033d-456a-ac5a-a0de7dd4462b.png">

**Comment by Subhash91134857** [comment]
issued has been fixed.
